### ISSUE TITLE
I can disambiguate links by providing an **as:** descriptor in an instance_group template

### ISSUE THREAD

**Issue by chendrix** [pivotal-cf/kiln#11]
we had to duplicate a job template in order to change the links provided by a job.

In bosh, you can actually specify at the instance_group level that the same job on different instance_groups provides different links, like this:

# ...
instance_groups:
- name: database_1
  jobs:
  - name: database_job
    release: ...
    provides:
      database_conn: {as: db1}
- name: database_2
  jobs:
  - name: database_job
    release: ...
    provides:
      database_conn: {as: db2}
- name: application_ig
  jobs:
  - name: application_job_two_db
    release: ...
    consumes:
      frontend_database: {from: db1}
      backend_database: {from: db2}
# ...
(from bosh.io links)

It would be great to be able to have this ability when creating a tile via kiln.

**Comment by chendrix** [comment]
We would have done it by using the feature provided by this issue instead of duplicating the file.

Also preliminary testing of our earlier method of doing it doesn't seem to have worked **anyways**, so this feature may actually be a blocking requirement for the c2c networking story.

**Comment by mcwumbly** [comment]
Gotcha.  If you validate that this will fix the issue (perhaps by hand-editing the bosh manifest or whatever), then we should definitely bump this up in priority.

**Comment by chendrix** [comment]
I was wrong, this **is not** a blocking requirement. But it would be a nice to have, to prevent the duplication of files.

**Comment by michelleheh** [comment]
A proposal to have **kiln bake** support the `provides` keyword. An `instance_group` template  can look like the following:
```
---
name: some-vm
label: Some Label
...
templates:
- $( job "some-job", provides: {"some-link": {"as": "some-link", "shared": true}, "some-other-link": {"as": "some-other-link", "shared": true} )
- $( job "some-other-job" )
...
```
The expected metadata should look like the following:
```
instance_groups:
- name: some-vm
  jobs:
  - name: some-job
    release: ...
    provides: |
      some-link: {as: some-link, shared: true}
      some-other-link: {as: some-other-link, shared: true}
- name: database_2
  jobs:
  - name: some-other_job
    release: ...
```
