### ISSUE TITLE
Error with kiln fetch with on-prem s3 compatible storage

### ISSUE THREAD

**Issue by cwb124** [pivotal-cf/kiln#42]
Hi folks, I am trying to get kiln fetch to work with my on-prem s3 compatible storage. I know it may not officially be supported but I spoke to Matt a few weeks back and he said there is an undocumented 'endpoint' param you can put in your kilnlock file that allowed him to use local s3 at one point.  I am a little foggy on whether or not region is required since I am on-prem but I've tried it with and without and the error doesn't change so I don't believe that's it.   Just hoping maybe someone can look at my error and point me in the right direction.  Would appreciate it.  Here is my kilnfile:

```
release_sources:
  - type: s3
    publishable: true
    compiled: true
    endpoint: http://s3.na.mycompany.net
    bucket: MYBUCKET
    access_key_id: <ACCESS_KEY>
    secret_access_key: <SECRET_ACCESS_KEY>
    path_template: path_template: MYFOLDER/{{trimSuffix .Name "-release"}}/{{.Name}}-{{.Version}}-{{.StemcellOS}}-{{.StemcellVersion}}.tgz
```

When I run **kiln fetch --kilnfile kilnfile --releases-directory releases/** I get the following error:

WARNING - the "allow-only-publishable-releases" flag was not set.  Some fetched releases may be intended for development/testing only.
Found 5 missing releases to download.
Could not execute "fetch" download failed: couldn't find a release source with ID "". Available choices: ["MYBUCKET"]
