### ISSUE TITLE
Support ODB metadata

### ISSUE THREAD

**Issue by alex-slynko** [pivotal-cf/kiln#6]
We are using `kiln` to generate tile that uses the on-demand broker.
We have to specify release name and version in the manifest as well as a list of jobs. https://docs.pivotal.io/svc-sdk/odb/0-19/operating.html#catalog

We can't use `$( release "my-release")` because we need to specify additional properties. 
This is what we got in the manifest
```
releases:
- { "name": "my-release", "version": 42 }
  jobs: ["some", "jobs"]
```
It is not parseable.

Is there a workaround? Do you want us to work on the PR for this issue?

**Comment by mcwumbly** [comment]
@alex-slynko we chatted about this a bit this morning and were wondering whether it'd be sufficient to add something like `$( release-version "my-release")`.  We think we have other use cases for this.

For example, you would just hard code the release name, but then interpolate the version here:

```
service_deployment:
  releases:
    - name: my-release
      version: $( release-version "my-release" )
      jobs: [some, jobs]
```

In the mean time, the workaround is to just not use any of our interpolation syntax for this part of your tile recipe and just do:


```
service_deployment:
  releases:
    - name: my-release
      version: some-version
      jobs: [some, jobs]
```
